/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.Proyeccion;

import entidades.Pelicula;
import entidades.Proyeccion;
import entidades.Sala;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import listeners.RefreshListener;
import persistencia.Context;
import persistencia.PeliculaData;
import persistencia.SalaData;

/**
 *
 * @author Morbo
 */
public class AgregarProyeccionOk extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarProyeccionOk
     */
    private SalaData salaData = Context.getSalaData();
    private PeliculaData peliculaData = Context.getPeliculaData();
    private RefreshListener listener;

    public void setRefreshListener(RefreshListener listener) {
        this.listener = listener;
    }

    SpinnerDateModel modelHoraInicio = new SpinnerDateModel();
    SpinnerDateModel modelHoraFin = new SpinnerDateModel();
    public AgregarProyeccionOk() {
        initComponents();

        spinInicio.setModel(modelHoraInicio);
        JSpinner.DateEditor timeEditorInicio = new JSpinner.DateEditor(spinInicio, "HH:mm");
        spinInicio.setEditor(timeEditorInicio);

        spinFin.setModel(modelHoraFin);
        JSpinner.DateEditor timeEditorFin = new JSpinner.DateEditor(spinFin, "HH:mm");
        spinFin.setEditor(timeEditorFin);

        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent e) {
                txtPrecio.setText(txtPrecio.getText().replaceAll("[^0-9.]", ""));
            }
        });

        cargarComboSalas();
        cargarComboPeliculas();
    }
    
    private void limpiarCampos() {
        cbxSala.setSelectedIndex(0);
        cbxPelicula.setSelectedIndex(0);
        bgrp3D.clearSelection();
        bgrpSub.clearSelection();
        dateFecha.setDate(null);
        ((JSpinner.DefaultEditor) spinInicio.getEditor()).getTextField().setText("");
        ((JSpinner.DefaultEditor) spinFin.getEditor()).getTextField().setText("");
        txtPrecio.setText("");
    }

    private void cargarComboSalas() {
        List<Sala> salas = salaData.listarSalasActivas();
        for (Sala s : salas) {
            cbxSala.addItem(s);
        }
    }

    private void cargarComboPeliculas() {
        List<Pelicula> peliculas = peliculaData.obtenerPeliculasEnCartelera();
        cbxPelicula.removeAllItems();
        Pelicula peliculaNull = new Pelicula();
        peliculaNull.setTitulo("Seleccione...");
        cbxPelicula.addItem(peliculaNull);
        for (Pelicula pelicula : peliculas) {
            cbxPelicula.addItem(pelicula);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrp3D = new javax.swing.ButtonGroup();
        bgrpSub = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        dateFecha = new com.toedter.calendar.JDateChooser();
        lblInicio = new javax.swing.JLabel();
        spinInicio = new javax.swing.JSpinner();
        lblFin = new javax.swing.JLabel();
        spinFin = new javax.swing.JSpinner();
        cbxSala = new javax.swing.JComboBox<>();
        cbxPelicula = new javax.swing.JComboBox<>();
        cbxIdioma = new javax.swing.JComboBox<>();
        bSi = new javax.swing.JRadioButton();
        bNo = new javax.swing.JRadioButton();
        bNo1 = new javax.swing.JRadioButton();
        bSi1 = new javax.swing.JRadioButton();
        txtPrecio = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        lblSubtitulada = new javax.swing.JLabel();
        lbl3D = new javax.swing.JLabel();
        lblIdioma = new javax.swing.JLabel();
        lblPelicula = new javax.swing.JLabel();
        lblSala1 = new javax.swing.JLabel();
        btnGurardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(676, 536));
        setPreferredSize(new java.awt.Dimension(676, 536));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Agregar Sala.png"))); // NOI18N
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -50, 520, 200));

        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(204, 153, 0));
        lblFecha.setText("Fecha:");
        jPanel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 90, 20));
        jPanel1.add(dateFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 170, 130, -1));

        lblInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(204, 153, 0));
        lblInicio.setText("Inicio:");
        jPanel1.add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 90, 20));
        jPanel1.add(spinInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 170, 80, -1));

        lblFin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFin.setForeground(new java.awt.Color(204, 153, 0));
        lblFin.setText("Fin:");
        jPanel1.add(lblFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 90, 20));
        jPanel1.add(spinFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 80, -1));

        jPanel1.add(cbxSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 170, -1));

        jPanel1.add(cbxPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 170, -1));

        cbxIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Inglés" }));
        jPanel1.add(cbxIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 170, -1));

        bgrp3D.add(bSi);
        bSi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bSi.setText("Si");
        bSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiActionPerformed(evt);
            }
        });
        jPanel1.add(bSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        bgrp3D.add(bNo);
        bNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bNo.setText("No");
        bNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNoActionPerformed(evt);
            }
        });
        jPanel1.add(bNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        bgrpSub.add(bNo1);
        bNo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bNo1.setText("No");
        bNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNo1ActionPerformed(evt);
            }
        });
        jPanel1.add(bNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        bgrpSub.add(bSi1);
        bSi1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bSi1.setText("Si");
        bSi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSi1ActionPerformed(evt);
            }
        });
        jPanel1.add(bSi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        txtPrecio.setToolTipText("");
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 170, -1));

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(204, 153, 0));
        lblPrecio.setText("Precio:");
        jPanel1.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        lblSubtitulada.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSubtitulada.setForeground(new java.awt.Color(204, 153, 0));
        lblSubtitulada.setText("Subtitulada:");
        jPanel1.add(lblSubtitulada, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        lbl3D.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl3D.setForeground(new java.awt.Color(204, 153, 0));
        lbl3D.setText("3D:");
        jPanel1.add(lbl3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 20, -1));

        lblIdioma.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIdioma.setForeground(new java.awt.Color(204, 153, 0));
        lblIdioma.setText("Idioma:");
        jPanel1.add(lblIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 50, 20));

        lblPelicula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPelicula.setForeground(new java.awt.Color(204, 153, 0));
        lblPelicula.setText("Pelicula:");
        jPanel1.add(lblPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 90, 20));

        lblSala1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSala1.setForeground(new java.awt.Color(204, 153, 0));
        lblSala1.setText("Sala:");
        jPanel1.add(lblSala1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 90, 20));

        btnGurardar.setBackground(new java.awt.Color(156, 163, 175));
        btnGurardar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnGurardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Guardar.png"))); // NOI18N
        btnGurardar.setText("Guardar");
        btnGurardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGurardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGurardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGurardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 160, 40));

        btnSalir.setBackground(new java.awt.Color(7, 10, 20));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Salir2.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(153, 153, 153)));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSiActionPerformed

    private void bNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bNoActionPerformed

    private void bNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bNo1ActionPerformed

    private void bSi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSi1ActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void btnGurardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGurardarActionPerformed
        Sala sala = (Sala) cbxSala.getSelectedItem();
        Pelicula pelicula = (Pelicula) cbxPelicula.getSelectedItem();
        java.util.Date fechaFuncion = dateFecha.getDate();
        Object inicio = spinInicio.getValue();
        Object fin = spinFin.getValue();
        String idioma = (String) cbxIdioma.getSelectedItem();
        String precioStr = txtPrecio.getText();

        if (sala == null || pelicula == null || fechaFuncion == null
            || inicio == null || fin == null || idioma == null || precioStr.isEmpty()
            || (!bSi.isSelected() && !bNo.isSelected())
            || (!bSi1.isSelected() && !bNo1.isSelected())) {
            JOptionPane.showMessageDialog(this, "complete todos los campos.");
            return;
        }

        LocalDate fechaLocal = fechaFuncion.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalTime horaInicio = ((Date) inicio).toInstant().atZone(ZoneId.systemDefault()).toLocalTime();
        LocalTime horaFin = ((Date) fin).toInstant().atZone(ZoneId.systemDefault()).toLocalTime();

        boolean es3D = bSi.isSelected();
        boolean subtitulada = bSi1.isSelected();
        double precio = Double.parseDouble(precioStr);

        if (fechaLocal.isBefore(LocalDate.now())) {
            JOptionPane.showMessageDialog(this, "La fecha de la función no puede ser anterior al día de hoy.");
            return;
        }

        if (!horaFin.isAfter(horaInicio)) {
            JOptionPane.showMessageDialog(this, "La hora de fin debe ser posterior a la hora de inicio.");
            return;
        }

        Proyeccion proy = new Proyeccion();
        proy.setSala(sala);
        proy.setPelicula(pelicula);
        proy.setFecha(fechaLocal);
        proy.setHoraInicio(horaInicio);
        proy.setHoraFin(horaFin);
        proy.setIdioma(idioma);
        proy.setEs3D(es3D);
        proy.setSubtitulada(subtitulada);
        proy.setPrecio(precio);

        boolean creada = Context.getProyeccionData().guardarProyeccion(proy);

        if (creada) {
            JOptionPane.showMessageDialog(this,
                "Proyección guardada correctamente.",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE
            );
            limpiarCampos();
            if (listener != null) {
                listener.actualizarLista();
            }
            this.dispose();
        }
    }//GEN-LAST:event_btnGurardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bNo;
    private javax.swing.JRadioButton bNo1;
    private javax.swing.JRadioButton bSi;
    private javax.swing.JRadioButton bSi1;
    private javax.swing.ButtonGroup bgrp3D;
    private javax.swing.ButtonGroup bgrpSub;
    private javax.swing.JButton btnGurardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxIdioma;
    private javax.swing.JComboBox<Pelicula> cbxPelicula;
    private javax.swing.JComboBox<Sala> cbxSala;
    private com.toedter.calendar.JDateChooser dateFecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl3D;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFin;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblPelicula;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSala1;
    private javax.swing.JLabel lblSubtitulada;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JSpinner spinFin;
    private javax.swing.JSpinner spinInicio;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
