/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import entidades.Sala;
import javax.swing.JOptionPane;
import persistencia.Context;
import persistencia.SalaData;
/**
 *
 * @author Manuel Zuñiga
 */
public class AgregarSalas extends javax.swing.JInternalFrame {

    private SalaData salaData = Context.getSalaData();

    public AgregarSalas() {
        initComponents();
        setTitle("Agregar Sala");
        configurarFormulario();
    }

    private void configurarFormulario() {
        jLabel4.setText("Nro de Sala:");
        jLabel5.setText("Capacidad:");
        lbl3D.setText("Disponibilidad 3D:");
        lblEstado.setText("Estado:");

        bSi.setText("Sí");
        bNo.setText("No");
        bSi1.setText("Activa");
        bNo1.setText("Inactiva");

    }

    private void limpiarCampos() {
        txtNroSala.setText("");
        txtCapacidad.setText("");
        botones.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botones = new javax.swing.ButtonGroup();
        panel1 = new java.awt.Panel();
        txtNroSala = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnGurardar = new javax.swing.JButton();
        txtCapacidad = new javax.swing.JTextField();
        bSi = new javax.swing.JRadioButton();
        bNo = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl3D = new javax.swing.JLabel();
        bSi1 = new javax.swing.JRadioButton();
        bNo1 = new javax.swing.JRadioButton();
        lblEstado = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 0, 51));

        panel1.setBackground(new java.awt.Color(51, 51, 51));
        panel1.setForeground(new java.awt.Color(38, 64, 107));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNroSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNroSalaActionPerformed(evt);
            }
        });
        panel1.add(txtNroSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 170, -1));

        btnSalir.setBackground(new java.awt.Color(7, 10, 20));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Salir2.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(153, 153, 153)));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 150, 40));

        btnGurardar.setBackground(new java.awt.Color(156, 163, 175));
        btnGurardar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnGurardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Guardar.png"))); // NOI18N
        btnGurardar.setText("Guardar");
        btnGurardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGurardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGurardarActionPerformed(evt);
            }
        });
        panel1.add(btnGurardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 160, 40));

        txtCapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapacidadActionPerformed(evt);
            }
        });
        panel1.add(txtCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 170, 30));

        bSi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bSi.setText("Si");
        bSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiActionPerformed(evt);
            }
        });
        panel1.add(bSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        bNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bNo.setText("No");
        bNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNoActionPerformed(evt);
            }
        });
        panel1.add(bNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        jLabel4.setText("Numero de sala");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 90, 20));

        jLabel5.setText("Capacidad");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 90, 20));

        lbl3D.setText("3D");
        panel1.add(lbl3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        bSi1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bSi1.setText("Activa");
        bSi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSi1ActionPerformed(evt);
            }
        });
        panel1.add(bSi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        bNo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bNo1.setText("Inactiva");
        bNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNo1ActionPerformed(evt);
            }
        });
        panel1.add(bNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        lblEstado.setText("Estado");
        panel1.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNroSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNroSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNroSalaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGurardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGurardarActionPerformed
            int nroSala = Integer.parseInt(txtNroSala.getText().trim());
            int capacidad = Integer.parseInt(txtCapacidad.getText().trim());
            boolean apta3D = bSi.isSelected();
            boolean estado = true;
            Sala s = new Sala();
            s.setNroSala(nroSala);
            s.setCapacidad(capacidad);
            s.setApta3D(apta3D);
            s.setEstado(estado);
            salaData.guardarSala(s);
            limpiarCampos();
            this.dispose();
    }//GEN-LAST:event_btnGurardarActionPerformed

    private void txtCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadActionPerformed

    private void bNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bNoActionPerformed

    private void bSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSiActionPerformed

    private void bSi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSi1ActionPerformed

    private void bNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bNo1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bNo;
    private javax.swing.JRadioButton bNo1;
    private javax.swing.JRadioButton bSi;
    private javax.swing.JRadioButton bSi1;
    private javax.swing.ButtonGroup botones;
    private javax.swing.JButton btnGurardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbl3D;
    private javax.swing.JLabel lblEstado;
    private java.awt.Panel panel1;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtNroSala;
    // End of variables declaration//GEN-END:variables
}
