
package vistas;

import entidades.Pelicula;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.PeliculaData;


/**
 *
 * @author ernesto
 */
public class BuscarPelicula extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarPelicula
     */
    private PeliculaData peliculaData;
    private Peliculas panelPeliculas;
    
    public BuscarPelicula(Peliculas panelPeliculas) {
        initComponents();

    }
    
      public void BuscarPelicula() {
        try {
            String titulo = txtTitulo.getText().trim();
            String genero = (String) cbxGenero.getSelectedItem();
            String carteleraSeleccion = (String) cbxCartelera.getSelectedItem();
            Integer enCartelera = null;

            // convertir selección de cartelera a entero
            if (carteleraSeleccion.equalsIgnoreCase("Sí")) {
                enCartelera = 1;
            } else if (carteleraSeleccion.equalsIgnoreCase("No")) {
                enCartelera = 0;
            }

            // buscar en la base de datos
            List<Pelicula> peliculasBuscadas = peliculaData.buscarPeliculas(titulo, genero, enCartelera);

            // limpiar la tabla del panel Peliculas
            DefaultTableModel modelo = (DefaultTableModel) panelPeliculas.jtblePeliculas.getModel();
            modelo.setRowCount(0);

            // llenar tabla con resultados
            for (Pelicula p : peliculasBuscadas) {
                modelo.addRow(new Object[]{
                    p.getIdPelicula(),
                    p.getTitulo(),
                    p.getGenero(),
                    p.getEnCartelera() == 1 ? "Sí" : "No"
                });
            }

            if (peliculasBuscadas.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se encontraron películas con esos filtros.");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "no se encontraron peliculas: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlbuscarPeli = new javax.swing.JPanel();
        lblbuscarPeli = new javax.swing.JLabel();
        txtnombrePeli = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JButton();
        cbxGenero = new javax.swing.JComboBox<>();
        cbxCartelera = new javax.swing.JComboBox<>();
        lblGenero = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        lblbuscarPeli.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblbuscarPeli.setText("Buscar");
        lblbuscarPeli.setMaximumSize(new java.awt.Dimension(140, 25));
        lblbuscarPeli.setMinimumSize(new java.awt.Dimension(140, 25));
        lblbuscarPeli.setName(""); // NOI18N

        txtTitulo.setText("Titulo:");

        btnbuscar.setText("Buscar");

        cbxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxCartelera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblGenero.setText("Genero:");

        jLabel1.setText("Cartelera:");

        javax.swing.GroupLayout pnlbuscarPeliLayout = new javax.swing.GroupLayout(pnlbuscarPeli);
        pnlbuscarPeli.setLayout(pnlbuscarPeliLayout);
        pnlbuscarPeliLayout.setHorizontalGroup(
            pnlbuscarPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlbuscarPeliLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(lblbuscarPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlbuscarPeliLayout.createSequentialGroup()
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnombrePeli, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxCartelera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnbuscar)
                .addGap(70, 70, 70))
        );
        pnlbuscarPeliLayout.setVerticalGroup(
            pnlbuscarPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlbuscarPeliLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblbuscarPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlbuscarPeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombrePeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitulo)
                    .addComponent(btnbuscar)
                    .addComponent(lblGenero)
                    .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cbxCartelera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(269, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlbuscarPeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlbuscarPeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JComboBox<String> cbxCartelera;
    private javax.swing.JComboBox<String> cbxGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblbuscarPeli;
    private javax.swing.JPanel pnlbuscarPeli;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JTextField txtnombrePeli;
    // End of variables declaration//GEN-END:variables
}
