/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import vistas.Cartelera.Cartelera;
import java.awt.Color;
import persistencia.Conexion;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.border.Border;
import persistencia.Context;
import vistas.ComprarEntradas.ComprarEntradaF;
import vistas.ComprarEntradasOnline.ComprarEntradasOnline;
import vistas.ticket.ImprimirTickets;
import vistas.ticket.Tickets;

/**
 *
 * @author PC
 */
public class CinemaCentro extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CinemaCentro.class.getName());

    public CinemaCentro() {
        initComponents();
        escritorio.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        Conexion con = new Conexion("jdbc:mariadb://localhost:3306/cinemacentro_g13", "root", "");
        Context.inicializar(con);
        ImageIcon fondoIcono = new ImageIcon(getClass().getResource("/images/fnd.png"));
        JLabel fondo = new JLabel(fondoIcono);
        fondo.setBounds(0, 0, fondoIcono.getIconWidth(), fondoIcono.getIconHeight());
        fondo.setBorder(BorderFactory.createLineBorder(new Color(8, 64, 107), 1));
        escritorio.add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);

        Color azulNoche = new Color(11, 28, 56);
        Color azulAcero = new Color(31, 45, 74);
        Color azulOscuro = new Color(7, 10, 20);
        Color blancoHumo = new Color(242, 242, 242);
        Color grisCine = new Color(156, 163, 175);
        Color rojoCine = new Color(214, 69, 69);
        Color azulTenue = new Color(38, 64, 107);

        getContentPane().setBackground(azulNoche);
        pnlHeader.setBackground(azulNoche);
        pnlMenu.setBackground(azulTenue);
        pnlTitulo.setBackground(azulTenue);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        btnOnline = new javax.swing.JButton();
        btnCartelera = new javax.swing.JButton();
        btnAdministracion = new javax.swing.JButton();
        btnEntradas1 = new javax.swing.JButton();
        btnTickets = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(41, 75, 74));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        pnlHeader.setBackground(new java.awt.Color(30, 41, 59));
        pnlHeader.setForeground(new java.awt.Color(30, 41, 59));
        pnlHeader.setLayout(new java.awt.BorderLayout());

        pnlTitulo.setForeground(new java.awt.Color(30, 41, 59));
        pnlTitulo.setLayout(new java.awt.GridLayout(1, 0));

        lblTitulo.setBackground(new java.awt.Color(8, 64, 107));
        lblTitulo.setForeground(new java.awt.Color(8, 64, 107));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Titulo.png"))); // NOI18N
        lblTitulo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlTitulo.add(lblTitulo);

        pnlHeader.add(pnlTitulo, java.awt.BorderLayout.CENTER);

        pnlMenu.setBackground(new java.awt.Color(30, 41, 59));
        pnlMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMenu.setForeground(null);

        btnOnline.setBackground(new java.awt.Color(0, 0, 0));
        btnOnline.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnOnline.setForeground(new java.awt.Color(204, 204, 204));
        btnOnline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Online (2).png"))); // NOI18N
        btnOnline.setText("Entradas Online");
        btnOnline.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOnline.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOnline.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Online.png"))); // NOI18N
        btnOnline.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Online.png"))); // NOI18N
        btnOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnlineActionPerformed(evt);
            }
        });

        btnCartelera.setBackground(new java.awt.Color(0, 0, 0));
        btnCartelera.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnCartelera.setForeground(new java.awt.Color(204, 204, 204));
        btnCartelera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cartelera.png"))); // NOI18N
        btnCartelera.setText("Cartelera");
        btnCartelera.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCartelera.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCartelera.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cartelera.png"))); // NOI18N
        btnCartelera.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cartelera75.png"))); // NOI18N
        btnCartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarteleraActionPerformed(evt);
            }
        });

        btnAdministracion.setBackground(new java.awt.Color(0, 0, 0));
        btnAdministracion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAdministracion.setForeground(new java.awt.Color(204, 204, 204));
        btnAdministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Admin.png"))); // NOI18N
        btnAdministracion.setText("Administracion");
        btnAdministracion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdministracion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdministracion.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Admin.png"))); // NOI18N
        btnAdministracion.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Admin75.png"))); // NOI18N
        btnAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministracionActionPerformed(evt);
            }
        });

        btnEntradas1.setBackground(new java.awt.Color(0, 0, 0));
        btnEntradas1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnEntradas1.setForeground(new java.awt.Color(204, 204, 204));
        btnEntradas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tickets (2).png"))); // NOI18N
        btnEntradas1.setText("Entradas");
        btnEntradas1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEntradas1.setHideActionText(true);
        btnEntradas1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEntradas1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tickets (2).png"))); // NOI18N
        btnEntradas1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TIcket76.png"))); // NOI18N
        btnEntradas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradas1ActionPerformed(evt);
            }
        });

        btnTickets.setBackground(new java.awt.Color(0, 0, 0));
        btnTickets.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnTickets.setForeground(new java.awt.Color(204, 204, 204));
        btnTickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ticketsss.png"))); // NOI18N
        btnTickets.setText("Tickets");
        btnTickets.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTickets.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTickets.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ticketsss.png"))); // NOI18N
        btnTickets.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/777TICK.png"))); // NOI18N
        btnTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEntradas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOnline, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(btnCartelera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdministracion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTickets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnEntradas1)
                .addGap(26, 26, 26)
                .addComponent(btnCartelera)
                .addGap(18, 18, 18)
                .addComponent(btnTickets)
                .addGap(18, 18, 18)
                .addComponent(btnOnline)
                .addGap(18, 18, 18)
                .addComponent(btnAdministracion)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        escritorio.setBackground(new java.awt.Color(8, 64, 107));
        escritorio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        escritorio.setForeground(new java.awt.Color(8, 64, 107));
        escritorio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        escritorio.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(escritorio)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(escritorio)
                    .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnlineActionPerformed
        ComprarEntradasOnline comprarEntrada = new ComprarEntradasOnline();
        abrirYCentrar(comprarEntrada);
    }//GEN-LAST:event_btnOnlineActionPerformed

    private void btnCarteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarteleraActionPerformed
        Cartelera cartelera= new Cartelera();
        abrirYCentrar(cartelera);
    }//GEN-LAST:event_btnCarteleraActionPerformed

    private void btnAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministracionActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        abrirYCentrar(login);


    }//GEN-LAST:event_btnAdministracionActionPerformed

    private void btnEntradas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradas1ActionPerformed
        ComprarEntradaF comprarEntrada = new ComprarEntradaF();
        abrirYCentrar(comprarEntrada);
    }//GEN-LAST:event_btnEntradas1ActionPerformed

    private void btnTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketsActionPerformed
       ImprimirTickets tickets=new ImprimirTickets();
       abrirYCentrar(tickets);
    }//GEN-LAST:event_btnTicketsActionPerformed

    /**
     * @param args the command line arguments
     */
    private void abrirYCentrar(JInternalFrame frame) {
        escritorio.add(frame);
        frame.pack();
        frame.setVisible(true);

        int x = (escritorio.getWidth() - frame.getWidth()) / 2;
        int y = (escritorio.getHeight() - frame.getHeight()) / 2;
        frame.setLocation(x, y);
    }

    public JDesktopPane getEscritorio() {
        return escritorio;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CinemaCentro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministracion;
    private javax.swing.JButton btnCartelera;
    private javax.swing.JButton btnEntradas1;
    private javax.swing.JButton btnOnline;
    private javax.swing.JButton btnTickets;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlTitulo;
    // End of variables declaration//GEN-END:variables
}
