/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.Color;
import persistencia.Conexion;
import java.sql.Connection;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.border.Border;
import persistencia.PeliculaData;

/**
 *
 * @author PC
 */
public class CinemaCentro extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CinemaCentro.class.getName());
    private Connection connection;

    private PeliculaData peliculaData;

    public CinemaCentro() {
        initComponents();
        Conexion con = new Conexion("jdbc:mariadb://localhost:3306/cinemacentro_g13", "root", "");

        peliculaData = new PeliculaData(con);
        ImageIcon fondoIcono = new ImageIcon(getClass().getResource("/images/background.png"));
        JLabel fondo = new JLabel(fondoIcono);
        fondo.setBounds(0, 0, fondoIcono.getIconWidth(), fondoIcono.getIconHeight());
        fondo.setBorder(BorderFactory.createLineBorder(new Color(217, 192, 217), 1));
        escritorio.add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        getContentPane().setBackground(new Color(1, 0, 15));
        pnlHeader.setBackground(new Color(1, 0, 15));
        pnlMenu.setBackground(new Color(1, 0, 15));
        pnlTitulo.setBackground(new Color(1, 0, 15));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        btnOnline = new javax.swing.JButton();
        btnEntradas = new javax.swing.JButton();
        btnAdministracion = new javax.swing.JButton();
        btnEntradas1 = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(30, 41, 59));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        pnlHeader.setBackground(new java.awt.Color(30, 41, 59));
        pnlHeader.setForeground(new java.awt.Color(30, 41, 59));
        pnlHeader.setLayout(new java.awt.BorderLayout());

        pnlTitulo.setForeground(new java.awt.Color(30, 41, 59));
        pnlTitulo.setLayout(new java.awt.GridLayout(1, 0));

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/titulo3 (1).png"))); // NOI18N
        pnlTitulo.add(lblTitulo);

        pnlHeader.add(pnlTitulo, java.awt.BorderLayout.CENTER);

        pnlMenu.setBackground(new java.awt.Color(30, 41, 59));
        pnlMenu.setForeground(new java.awt.Color(30, 41, 59));

        btnOnline.setBackground(new java.awt.Color(0, 0, 0));
        btnOnline.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnOnline.setForeground(new java.awt.Color(0, 48, 177));
        btnOnline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/online.png"))); // NOI18N
        btnOnline.setText("Entradas Online");
        btnOnline.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255))));
        btnOnline.setContentAreaFilled(false);
        btnOnline.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnlineActionPerformed(evt);
            }
        });

        btnEntradas.setBackground(new java.awt.Color(0, 0, 0));
        btnEntradas.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnEntradas.setForeground(new java.awt.Color(0, 48, 177));
        btnEntradas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clapperboard.png"))); // NOI18N
        btnEntradas.setText("Cartelera");
        btnEntradas.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255))));
        btnEntradas.setContentAreaFilled(false);
        btnEntradas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradasActionPerformed(evt);
            }
        });

        btnAdministracion.setBackground(new java.awt.Color(0, 0, 0));
        btnAdministracion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAdministracion.setForeground(new java.awt.Color(0, 48, 177));
        btnAdministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings.png"))); // NOI18N
        btnAdministracion.setText("Administracion");
        btnAdministracion.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255))));
        btnAdministracion.setContentAreaFilled(false);
        btnAdministracion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministracionActionPerformed(evt);
            }
        });

        btnEntradas1.setBackground(new java.awt.Color(0, 0, 0));
        btnEntradas1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnEntradas1.setForeground(new java.awt.Color(0, 48, 177));
        btnEntradas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ticket.png"))); // NOI18N
        btnEntradas1.setText("Entradas");
        btnEntradas1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255))));
        btnEntradas1.setContentAreaFilled(false);
        btnEntradas1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEntradas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradas1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOnline, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(btnEntradas, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(btnAdministracion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(btnEntradas1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnEntradas1)
                .addGap(79, 79, 79)
                .addComponent(btnEntradas)
                .addGap(83, 83, 83)
                .addComponent(btnOnline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdministracion)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(escritorio)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(escritorio)
                    .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOnlineActionPerformed

    private void btnEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntradasActionPerformed

    private void btnAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministracionActionPerformed
        // TODO add your handling code here:
        Login login = new Login(peliculaData);
        abrirYCentrar(login);


    }//GEN-LAST:event_btnAdministracionActionPerformed

    private void btnEntradas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradas1ActionPerformed

    }//GEN-LAST:event_btnEntradas1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void abrirYCentrar(JInternalFrame frame) {
        escritorio.add(frame);
        frame.pack();
        frame.setVisible(true);

        int x = (escritorio.getWidth() - frame.getWidth()) / 2;
        int y = (escritorio.getHeight() - frame.getHeight()) / 2;
        frame.setLocation(x, y);
    }

    public JDesktopPane getEscritorio() {
        return escritorio;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CinemaCentro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministracion;
    private javax.swing.JButton btnEntradas;
    private javax.swing.JButton btnEntradas1;
    private javax.swing.JButton btnOnline;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlTitulo;
    // End of variables declaration//GEN-END:variables
}
