/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.Color;
import persistencia.Conexion;
import java.sql.Connection;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.border.Border;
import persistencia.PeliculaData;

/**
 *
 * @author PC
 */
public class CinemaCentro extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CinemaCentro.class.getName());
    private Connection connection;

    private PeliculaData peliculaData;

    public CinemaCentro() {
        initComponents();
        Conexion con = new Conexion("jdbc:mariadb://localhost:3306/cinemacentro_g13", "root", "");

        peliculaData = new PeliculaData(con);
        ImageIcon fondoIcono = new ImageIcon(getClass().getResource("/images/background.png"));
      Color azulNoche = new Color(11, 28, 56);      // Fondo principal
Color azulAcero = new Color(31, 45, 74);      // Paneles laterales / header
Color azulOscuro = new Color(7, 10, 20);      // Contenido central
Color blancoHumo = new Color(242, 242, 242);  // Texto principal
Color grisCine = new Color(156, 163, 175);    // Texto secundario
Color rojoCine = new Color(214, 69, 69);      // Acentos o selección
Color azulTenue = new Color(38, 64, 107);     // Bordes suaves


getContentPane().setBackground(azulNoche);
pnlHeader.setBackground(azulNoche);
pnlMenu.setBackground(azulNoche);
pnlTitulo.setBackground(azulNoche);




    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        pnlTitulo = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        btnOnline = new javax.swing.JButton();
        btnEntradas = new javax.swing.JButton();
        btnAdministracion = new javax.swing.JButton();
        btnEntradas1 = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(41, 75, 74));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        pnlHeader.setBackground(new java.awt.Color(30, 41, 59));
        pnlHeader.setForeground(new java.awt.Color(30, 41, 59));
        pnlHeader.setLayout(new java.awt.BorderLayout());

        pnlTitulo.setForeground(new java.awt.Color(30, 41, 59));
        pnlTitulo.setLayout(new java.awt.GridLayout(1, 0));
        pnlHeader.add(pnlTitulo, java.awt.BorderLayout.CENTER);

        pnlMenu.setBackground(new java.awt.Color(11, 28, 56));
        pnlMenu.setForeground(new java.awt.Color(11, 28, 56));

        btnOnline.setBackground(new java.awt.Color(0, 0, 0));
        btnOnline.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnOnline.setForeground(new java.awt.Color(204, 204, 204));
        btnOnline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Online (2).png"))); // NOI18N
        btnOnline.setText("Entradas Online");
        btnOnline.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOnline.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOnline.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOnline.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Online (2).png"))); // NOI18N
        btnOnline.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ticket75.png"))); // NOI18N
        btnOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnlineActionPerformed(evt);
            }
        });

        btnEntradas.setBackground(new java.awt.Color(0, 0, 0));
        btnEntradas.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnEntradas.setForeground(new java.awt.Color(204, 204, 204));
        btnEntradas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Proyecto Creador de logotipos.png"))); // NOI18N
        btnEntradas.setText("Cartelera");
        btnEntradas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEntradas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntradas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEntradas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cartelera75.png"))); // NOI18N
        btnEntradas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Proyecto Creador de logotipos.png"))); // NOI18N
        btnEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradasActionPerformed(evt);
            }
        });

        btnAdministracion.setBackground(new java.awt.Color(0, 0, 0));
        btnAdministracion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAdministracion.setForeground(new java.awt.Color(204, 204, 204));
        btnAdministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Admin.png"))); // NOI18N
        btnAdministracion.setText("Administracion");
        btnAdministracion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdministracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdministracion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdministracion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Admin.png"))); // NOI18N
        btnAdministracion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Admin75.png"))); // NOI18N
        btnAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministracionActionPerformed(evt);
            }
        });

        btnEntradas1.setBackground(new java.awt.Color(0, 0, 0));
        btnEntradas1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnEntradas1.setForeground(new java.awt.Color(204, 204, 204));
        btnEntradas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tickets (2).png"))); // NOI18N
        btnEntradas1.setText("Entradas");
        btnEntradas1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEntradas1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntradas1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEntradas1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tickets (2).png"))); // NOI18N
        btnEntradas1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TIcket76.png"))); // NOI18N
        btnEntradas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradas1ActionPerformed(evt);
            }
        });

        escritorio.setBackground(new java.awt.Color(11, 28, 56));
        escritorio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        escritorio.setForeground(new java.awt.Color(11, 28, 56));
        escritorio.setToolTipText("");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOnline, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(btnEntradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdministracion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEntradas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(escritorio)
                .addContainerGap())
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEntradas1)
                .addGap(18, 18, 18)
                .addComponent(btnEntradas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOnline)
                .addGap(18, 18, 18)
                .addComponent(btnAdministracion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        btnEntradas1.getAccessibleContext().setAccessibleDescription("");

        lblTitulo.setBackground(new java.awt.Color(11, 28, 56));
        lblTitulo.setForeground(new java.awt.Color(11, 28, 56));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Proyecto Cambiar tamaño de imagen-1 (3).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 1224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblTitulo.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOnlineActionPerformed

    private void btnEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntradasActionPerformed

    private void btnAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministracionActionPerformed
        // TODO add your handling code here:
        Login login = new Login(peliculaData);
        abrirYCentrar(login);


    }//GEN-LAST:event_btnAdministracionActionPerformed

    private void btnEntradas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradas1ActionPerformed

    }//GEN-LAST:event_btnEntradas1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void abrirYCentrar(JInternalFrame frame) {
        escritorio.add(frame);
        frame.pack();
        frame.setVisible(true);

        int x = (escritorio.getWidth() - frame.getWidth()) / 2;
        int y = (escritorio.getHeight() - frame.getHeight()) / 2;
        frame.setLocation(x, y);
    }

    public JDesktopPane getEscritorio() {
        return escritorio;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CinemaCentro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministracion;
    private javax.swing.JButton btnEntradas;
    private javax.swing.JButton btnEntradas1;
    private javax.swing.JButton btnOnline;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlTitulo;
    // End of variables declaration//GEN-END:variables
}
