/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import entidades.Pelicula;
import entidades.Proyeccion;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import persistencia.Context;
import persistencia.LugaresData;
import persistencia.PeliculaData;
import persistencia.ProyeccionData;

/**
 *
 * @author Morbo
 */
public class DetallePelicula extends javax.swing.JInternalFrame {

    /**
     * Creates new form DetallePelicula
     */
    private PeliculaData peliculaData = Context.getPeliculaData();
    private ProyeccionData proyeccionData = Context.getProyeccionData();
    private LugaresData lugaresData = Context.getLugaresData();

    private Pelicula pelicula;
    private List<Proyeccion> proyecciones = new ArrayList<>();
    private HashMap<Proyeccion, Integer> lugaresDisponibles = new HashMap<>();

    public DetallePelicula(Pelicula pelicula) {
        this.pelicula = pelicula;
        initComponents();

        obtenerProyecciones();
        obtenerLugares();
        mostrarInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        pnlTituloPelicula = new javax.swing.JPanel();
        lblTituloPelicula = new javax.swing.JLabel();
        scrProyecciones = new javax.swing.JScrollPane();
        txtaProyecciones = new javax.swing.JTextArea();
        pblInfoPelicula = new javax.swing.JPanel();
        lblGenero = new javax.swing.JLabel();
        lblDirector = new javax.swing.JLabel();
        lblActores = new javax.swing.JLabel();
        lblGeneroInfo = new javax.swing.JLabel();
        lblDirectorInfo = new javax.swing.JLabel();
        lblActoresInfo = new javax.swing.JLabel();
        pnlProyecciones = new javax.swing.JPanel();
        lblProyeccionesDisponibles = new javax.swing.JLabel();

        setClosable(true);
        setMinimumSize(new java.awt.Dimension(655, 554));
        setPreferredSize(new java.awt.Dimension(655, 554));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        pnlHeader.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnlTituloPelicula.setBackground(new java.awt.Color(51, 51, 51));
        pnlTituloPelicula.setLayout(new java.awt.BorderLayout());

        lblTituloPelicula.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloPelicula.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloPelicula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlTituloPelicula.add(lblTituloPelicula, java.awt.BorderLayout.CENTER);

        scrProyecciones.setBackground(new java.awt.Color(51, 51, 51));

        txtaProyecciones.setBackground(new java.awt.Color(51, 51, 51));
        txtaProyecciones.setColumns(20);
        txtaProyecciones.setForeground(new java.awt.Color(255, 255, 255));
        txtaProyecciones.setRows(5);
        scrProyecciones.setViewportView(txtaProyecciones);

        pblInfoPelicula.setBackground(new java.awt.Color(51, 51, 51));

        lblGenero.setBackground(new java.awt.Color(255, 255, 255));
        lblGenero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGenero.setForeground(new java.awt.Color(255, 255, 255));
        lblGenero.setText("Genero:");

        lblDirector.setBackground(new java.awt.Color(255, 255, 255));
        lblDirector.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDirector.setForeground(new java.awt.Color(255, 255, 255));
        lblDirector.setText("Director:");

        lblActores.setBackground(new java.awt.Color(255, 255, 255));
        lblActores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblActores.setForeground(new java.awt.Color(255, 255, 255));
        lblActores.setText("Actores:");

        lblGeneroInfo.setBackground(new java.awt.Color(255, 255, 255));
        lblGeneroInfo.setForeground(new java.awt.Color(255, 255, 255));

        lblDirectorInfo.setBackground(new java.awt.Color(255, 255, 255));
        lblDirectorInfo.setForeground(new java.awt.Color(255, 255, 255));

        lblActoresInfo.setBackground(new java.awt.Color(255, 255, 255));
        lblActoresInfo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pblInfoPeliculaLayout = new javax.swing.GroupLayout(pblInfoPelicula);
        pblInfoPelicula.setLayout(pblInfoPeliculaLayout);
        pblInfoPeliculaLayout.setHorizontalGroup(
            pblInfoPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pblInfoPeliculaLayout.createSequentialGroup()
                .addGroup(pblInfoPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pblInfoPeliculaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblActores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblActoresInfo))
                    .addGroup(pblInfoPeliculaLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(pblInfoPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDirector)
                            .addGroup(pblInfoPeliculaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblGenero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pblInfoPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGeneroInfo)
                                    .addComponent(lblDirectorInfo))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pblInfoPeliculaLayout.setVerticalGroup(
            pblInfoPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pblInfoPeliculaLayout.createSequentialGroup()
                .addGroup(pblInfoPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenero)
                    .addComponent(lblGeneroInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pblInfoPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDirector)
                    .addComponent(lblDirectorInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pblInfoPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActores)
                    .addComponent(lblActoresInfo))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pnlProyecciones.setBackground(new java.awt.Color(51, 51, 51));
        pnlProyecciones.setLayout(new java.awt.BorderLayout());

        lblProyeccionesDisponibles.setBackground(new java.awt.Color(255, 255, 255));
        lblProyeccionesDisponibles.setForeground(new java.awt.Color(255, 255, 255));
        lblProyeccionesDisponibles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProyeccionesDisponibles.setText("🎬  PROYECCIÓNES DISPONIBLES");
        pnlProyecciones.add(lblProyeccionesDisponibles, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrProyecciones)
                    .addComponent(pnlProyecciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pblInfoPelicula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTituloPelicula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTituloPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pblInfoPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlProyecciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(scrProyecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void obtenerProyecciones() {
        proyecciones = proyeccionData.listarProyeccionesPorId(pelicula.getIdPelicula());
    }

    private void obtenerLugares() {
        if (proyecciones.size() > 0) {
            for (Proyeccion p : proyecciones) {
                Integer lugares = lugaresData.ObtenerLugaresDisponibles(p.getIdProyeccion());
                lugaresDisponibles.put(p, lugares);
            }
        }
    }

    private void mostrarInfo() {
        lblTituloPelicula.setText(pelicula.getTitulo());
        lblGeneroInfo.setText(pelicula.getGenero());
        lblDirectorInfo.setText(pelicula.getDirector());
        lblActoresInfo.setText(pelicula.getActores());

        if (lugaresDisponibles.size() > 0) {
            StringBuilder sb = new StringBuilder();

            for (Map.Entry<Proyeccion, Integer> entry : lugaresDisponibles.entrySet()) {
                Proyeccion p = entry.getKey();
                int lugaresLibres = entry.getValue();

                sb.append("───────────────────────────────\n");
                sb.append("         SALA ").append(p.getSala().getNroSala()).append("\n");
                sb.append("🗣️ Idioma: ").append(p.getIdioma()).append("\n");
                sb.append("🎞️ Es 3D: ").append(p.isEs3D() ? "Sí" : "No").append("\n");
                sb.append("💬 Subtitulada: ").append(p.isSubtitulada() ? "Sí" : "No").append("\n");
                sb.append("🕒 Inicio: ").append(p.getHoraInicio()).append("\n");
                sb.append("🕤 Fin: ").append(p.getHoraFin()).append("\n");
                sb.append("📅 Fecha: ").append(p.getFecha()).append("\n");
                sb.append("💲 Precio: $").append(p.getPrecio()).append("\n");
                sb.append("🎟️ Lugares libres: ").append(lugaresLibres).append("\n");
                sb.append("═══════════════════════════════\n\n");
            }

            txtaProyecciones.setText(sb.toString());
        } else {
            txtaProyecciones.setText("No hay proyecciones disponibles");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblActores;
    private javax.swing.JLabel lblActoresInfo;
    private javax.swing.JLabel lblDirector;
    private javax.swing.JLabel lblDirectorInfo;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblGeneroInfo;
    private javax.swing.JLabel lblProyeccionesDisponibles;
    private javax.swing.JLabel lblTituloPelicula;
    private javax.swing.JPanel pblInfoPelicula;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlProyecciones;
    private javax.swing.JPanel pnlTituloPelicula;
    private javax.swing.JScrollPane scrProyecciones;
    private javax.swing.JTextArea txtaProyecciones;
    // End of variables declaration//GEN-END:variables
}
