/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author Sistemas
 */
public class ModificarPelicula extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModificarPelicula
     */
    public ModificarPelicula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        lblDirector = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblActores = new javax.swing.JLabel();
        cbxGenero = new javax.swing.JComboBox<>();
        txtTitulo = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        lblOrigen = new javax.swing.JLabel();
        dateEstreno = new com.toedter.calendar.JDateChooser();
        lblGenero = new javax.swing.JLabel();
        btnGurardar = new javax.swing.JButton();
        lblEstreno = new javax.swing.JLabel();
        txtDirector = new javax.swing.JTextField();
        lblCartelera = new javax.swing.JLabel();
        txtActores = new javax.swing.JTextField();
        bSi = new javax.swing.JRadioButton();
        bNo = new javax.swing.JRadioButton();
        txtOrigen = new javax.swing.JTextField();
        Modificar = new javax.swing.JLabel();

        panel1.setBackground(new java.awt.Color(51, 51, 51));
        panel1.setForeground(new java.awt.Color(38, 64, 107));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDirector.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDirector.setForeground(new java.awt.Color(255, 204, 0));
        lblDirector.setText("Director:");
        panel1.add(lblDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, 20));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 204, 0));
        lblTitulo.setText("Titulo:");
        panel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, 20));

        lblActores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblActores.setForeground(new java.awt.Color(255, 204, 0));
        lblActores.setText("Actores:");
        panel1.add(lblActores, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, 20));

        cbxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxGeneroActionPerformed(evt);
            }
        });
        panel1.add(cbxGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 170, 30));

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });
        panel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 170, 30));

        btnSalir.setBackground(new java.awt.Color(102, 102, 102));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(204, 204, 204));
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 100, 30));

        lblOrigen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblOrigen.setForeground(new java.awt.Color(255, 204, 0));
        lblOrigen.setText("Origen:");
        panel1.add(lblOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, 20));
        panel1.add(dateEstreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 170, 30));

        lblGenero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGenero.setForeground(new java.awt.Color(255, 204, 0));
        lblGenero.setText("Genero:");
        panel1.add(lblGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, 20));

        btnGurardar.setBackground(new java.awt.Color(102, 0, 0));
        btnGurardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGurardar.setForeground(new java.awt.Color(204, 204, 204));
        btnGurardar.setText("Guardar");
        btnGurardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGurardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGurardarActionPerformed(evt);
            }
        });
        panel1.add(btnGurardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 100, 30));

        lblEstreno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstreno.setForeground(new java.awt.Color(255, 204, 0));
        lblEstreno.setText("Estreno:");
        panel1.add(lblEstreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, 20));

        txtDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirectorActionPerformed(evt);
            }
        });
        panel1.add(txtDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 170, 30));

        lblCartelera.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCartelera.setForeground(new java.awt.Color(255, 204, 0));
        lblCartelera.setText("En Cartelera:");
        panel1.add(lblCartelera, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, 20));
        panel1.add(txtActores, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 170, 30));

        bSi.setForeground(new java.awt.Color(255, 204, 51));
        bSi.setText("Si");
        bSi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiActionPerformed(evt);
            }
        });
        panel1.add(bSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, 20));

        bNo.setForeground(new java.awt.Color(255, 204, 51));
        bNo.setText("No");
        bNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNoActionPerformed(evt);
            }
        });
        panel1.add(bNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, 20));
        panel1.add(txtOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 170, 30));

        Modificar.setBackground(new java.awt.Color(31, 45, 74));
        Modificar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Modificar.setForeground(new java.awt.Color(204, 153, 0));
        Modificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Modificar.setText("Modificar Pelicula");
        Modificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Modificar.setOpaque(true);
        panel1.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 540, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGeneroActionPerformed

    }//GEN-LAST:event_cbxGeneroActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGurardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGurardarActionPerformed

      

    }//GEN-LAST:event_btnGurardarActionPerformed

    private void bSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSiActionPerformed

    private void bNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bNoActionPerformed

    private void txtDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirectorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Modificar;
    private javax.swing.JRadioButton bNo;
    private javax.swing.JRadioButton bSi;
    private javax.swing.JButton btnGurardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxGenero;
    private com.toedter.calendar.JDateChooser dateEstreno;
    private javax.swing.JLabel lblActores;
    private javax.swing.JLabel lblCartelera;
    private javax.swing.JLabel lblDirector;
    private javax.swing.JLabel lblEstreno;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblOrigen;
    private javax.swing.JLabel lblTitulo;
    private java.awt.Panel panel1;
    private javax.swing.JTextField txtActores;
    private javax.swing.JTextField txtDirector;
    private javax.swing.JTextField txtOrigen;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
