/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.ComprarEntradasOnline;

import entidades.Comprador;
import entidades.Lugar;
import entidades.Pelicula;
import entidades.Proyeccion;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.List;
import javax.swing.JPanel;
import listeners.EntradasListener;
import servicios.CompraServicio;
import vistas.ComprarEntradas.Confirmar;
import vistas.ComprarEntradas.DatosComprador;
import vistas.ComprarEntradas.SeleccionAsientos;
import vistas.ComprarEntradas.SeleccionPelicula;



/**
 *
 * @author tomas
 */
public class ComprarEntradasOnline extends javax.swing.JInternalFrame {

    /**
     * Creates new form ComprarEntradasOnline
     */
    private CompraServicio compraServicio = new CompraServicio();
    private Comprador comprador;
    private Proyeccion proyeccion;
    
    private int pasoActual = 1;
    private CardLayout layout;
    private EntradasListener listener;

    
    private List<Lugar> asientosSeleccionados;

    DatosCompradorOnline paso1;
    SeleccionPeliculaOnline paso2;
    SeleccionAsientosOnline paso3;
    DatosTarjeta paso4;
    ConfirmarOnline paso5;

    
    
    
    public ComprarEntradasOnline() {
        initComponents();
        aplicarEstiloOscuro();
        
        paso1 = new DatosCompradorOnline();
        paso2 = new SeleccionPeliculaOnline();
        paso3 = new SeleccionAsientosOnline();
        paso4 = new DatosTarjeta();
        paso5 = new ConfirmarOnline();

        pnlPrincipal.add(paso1, "paso1");
        pnlPrincipal.add(paso2, "paso2");
        pnlPrincipal.add(paso3, "paso3");
        pnlPrincipal.add(paso4, "paso4");
        pnlPrincipal.add(paso5,"paso5");

        btnAnterior.setEnabled(false);

        layout = (CardLayout) pnlPrincipal.getLayout();
    }
    
    private void aplicarEstiloOscuro() {
        Color fondoGeneral = new Color(33, 33, 33);
        Color panelOscuro = new Color(45, 45, 45);
        Color textoClaro = new Color(230, 230, 230);
        Color rojoCine = new Color(102,0,0);
        Color grisBoton = new Color(77, 77, 77);

    
        getContentPane().setBackground(fondoGeneral);
        setBackground(fondoGeneral);

        pnlPrincipal.setBackground(panelOscuro);

     
        btnSiguiente.setBackground(rojoCine);
        btnSiguiente.setForeground(Color.WHITE);
        btnSiguiente.setFocusPainted(false);
        btnSiguiente.setBorderPainted(false);


        btnAnterior.setBackground(grisBoton);
        btnAnterior.setForeground(Color.WHITE);
        btnAnterior.setFocusPainted(false);
        btnAnterior.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();

        setClosable(true);

        pnlPrincipal.setLayout(new java.awt.CardLayout());

        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setText("Siguente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAnterior)
                .addGap(26, 26, 26)
                .addComponent(btnSiguiente)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente)
                    .addComponent(btnAnterior))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
       avanzar();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
       volver();
    }//GEN-LAST:event_btnAnteriorActionPerformed
private void avanzar() {
     if(btnSiguiente.getText().equals("Guardar y Salir")){
         cargarDatos();
         this.dispose();
     }
        Component actual = pnlPrincipal.getComponent(pasoActual - 1);

        if (actual instanceof EntradasListener) {
            EntradasListener<?> listener = (EntradasListener<?>) actual;
            if (!listener.validarDatos()) {
                return;
            }
            Object datos = listener.guardarDatos();
            switch (pasoActual) {
                case 1:
                    comprador = (Comprador) datos;
                    break;
                case 2:
                    proyeccion = (Proyeccion) datos;
                    break;
                case 3:
                    asientosSeleccionados = (List<Lugar>) datos;
                    break;
                default:
                    break;
            }
        }

        if (pasoActual < 5) {
            pasoActual++;
            if (pasoActual == 3) {
                paso3.setProyeccionData(proyeccion.getIdProyeccion(), proyeccion.getPrecio());
            }
            if(pasoActual == 5) {
                paso5.setData(comprador, proyeccion, asientosSeleccionados);
            }
            
            layout.show(pnlPrincipal, "paso" + pasoActual);
            btnAnterior.setEnabled(true);
        }

        if (pasoActual == 4) {
            btnSiguiente.setText("Confirmar");
        }
        if(pasoActual ==5){
            btnSiguiente.setText("Guardar y Salir");
        }
        
    }

    private void volver() {
        if (pasoActual > 1) {
            pasoActual--;
            layout.show(pnlPrincipal, "paso" + pasoActual);

        if (pasoActual == 3) {
            paso3.limpiarSeleccion();
        }
        btnSiguiente.setText("Siguiente");
    }
        
        if (pasoActual == 1) {
            btnAnterior.setEnabled(false);
        }
        
    }
    private void cargarDatos() {
        boolean guardado = compraServicio.guardarCompra(comprador, asientosSeleccionados, proyeccion);
        if(guardado) {
            System.out.println("Guardado en bd correctamente");
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
