package VistaCartelera;

import entidades.Pelicula;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import listeners.PeliculaListener;
import org.mariadb.jdbc.Connection;
import persistencia.Context;
import persistencia.PeliculaData;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author tomas
 */
public class Cartelera extends javax.swing.JInternalFrame {

    
    private PeliculaData peliculaData = Context.getPeliculaData();
    private PeliculaListener listener;
    private DefaultTableModel modelo;
    private Connection connection;

    public Cartelera() {
        initComponents();
        tableCart.add("Peliculas En Cartelera",new PeliculasEnCartelera());
        tableCart.add("Proximos Estrenos", new ProximosEstrenos());
        
    }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableCart = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(33, 33, 33));
        setClosable(true);

        tableCart.setBackground(new java.awt.Color(33, 33, 33));
        tableCart.setForeground(new java.awt.Color(33, 33, 33));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableCart, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableCart, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tableCart;
    // End of variables declaration//GEN-END:variables
}
