/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.Comprador;

import com.toedter.calendar.JDateChooser;
import entidades.Comprador;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import persistencia.CompradorData;
import persistencia.Context;
/**
 *
 * @author Manuel Zuñiga
 */
public class AgregarComprador extends javax.swing.JInternalFrame {

   private CompradorData compradorData = Context.getCompradorData();

    public AgregarComprador() {
        initComponents();
        setTitle("Agregar Comprador");
        inicializarComboPago();
    }

    private void inicializarComboPago() {
        cbxMedioPago.removeAllItems();
        cbxMedioPago.addItem("Efectivo");
        cbxMedioPago.addItem("Tarjeta");
        cbxMedioPago.addItem("Transferencia");
    }

    private void limpiarCampos() {
        txtDni.setText("");
        txtNombre.setText("");
        jDateFecNac.setDate(null);
        txtPassword.setText("");
        cbxMedioPago.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        txtDni = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnGurardar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jlblPass = new javax.swing.JLabel();
        jlblMedioPago = new javax.swing.JLabel();
        jDateFecNac = new com.toedter.calendar.JDateChooser();
        cbxMedioPago = new javax.swing.JComboBox<>();
        jlblFecNac1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 0, 51));

        panel1.setBackground(new java.awt.Color(51, 51, 51));
        panel1.setForeground(new java.awt.Color(38, 64, 107));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });
        panel1.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 170, -1));

        btnSalir.setBackground(new java.awt.Color(7, 10, 20));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Salir2.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(153, 153, 153)));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 150, 40));

        btnGurardar.setBackground(new java.awt.Color(156, 163, 175));
        btnGurardar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnGurardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Guardar.png"))); // NOI18N
        btnGurardar.setText("Guardar");
        btnGurardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGurardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGurardarActionPerformed(evt);
            }
        });
        panel1.add(btnGurardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 160, 40));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        panel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 170, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 153, 0));
        jLabel4.setText("DNI:");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 90, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 153, 0));
        jLabel5.setText("Nombre:");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 90, 20));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        panel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 170, -1));

        jlblPass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlblPass.setForeground(new java.awt.Color(204, 153, 0));
        jlblPass.setText("Password:");
        panel1.add(jlblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 90, 20));

        jlblMedioPago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlblMedioPago.setForeground(new java.awt.Color(204, 153, 0));
        jlblMedioPago.setText("Medio De Pago:");
        jlblMedioPago.setToolTipText("");
        panel1.add(jlblMedioPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 90, 20));
        panel1.add(jDateFecNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 170, -1));

        cbxMedioPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panel1.add(cbxMedioPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 170, -1));

        jlblFecNac1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlblFecNac1.setForeground(new java.awt.Color(204, 153, 0));
        jlblFecNac1.setText("Fecha de nacimiento:");
        panel1.add(jlblFecNac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 120, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AgreCom.png"))); // NOI18N
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 630, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGurardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGurardarActionPerformed
            String dni = txtDni.getText().trim();
        String nombre = txtNombre.getText().trim();
        Date fecha = jDateFecNac.getDate();
        String password = txtPassword.getText().trim();
        String medioPago = cbxMedioPago.getSelectedItem().toString();

        if (dni.isEmpty() || nombre.isEmpty() || password.isEmpty() || fecha == null) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos.");
            return;
        }

        LocalDate fechaNac = fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        Comprador comprador = new Comprador();
        comprador.setDni(dni);
        comprador.setNombre(nombre);
        comprador.setFechaNac(fechaNac);
        comprador.setPassword(password);
        comprador.setMedioPago(medioPago);

        boolean insertado = compradorData.crearComprador(comprador);

        if (insertado) {
            JOptionPane.showMessageDialog(this, "Comprador agregado correctamente.");
            limpiarCampos();
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar el comprador.");
        }
    }//GEN-LAST:event_btnGurardarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGurardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxMedioPago;
    private com.toedter.calendar.JDateChooser jDateFecNac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jlblFecNac1;
    private javax.swing.JLabel jlblMedioPago;
    private javax.swing.JLabel jlblPass;
    private java.awt.Panel panel1;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
