/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.Pelicula;

import entidades.Pelicula;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import persistencia.Context;
import persistencia.PeliculaData;
import listeners.RefreshListener;

/**
 *
 * @author tomas
 */
public class AgregarPelicula extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarPelicula
     */
    private PeliculaData peliculaData = Context.getPeliculaData();
    private RefreshListener listener;

    public void setRefreshListener(RefreshListener listener) {
        this.listener = listener;
    }

    public AgregarPelicula() {
        initComponents();
        cargarComboGeneros();
        botones.add(bNo);
        botones.add(bSi);
    }

    private void cargarComboGeneros() {
        String[] generos = {
            "Todas",
            "Acción",
            "Animación",
            "Aventura",
            "Ciencia Ficción",
            "Comedia",
            "Comedia Romántica",
            "Documental",
            "Drama",
            "Fantasía",
            "Histórico",
            "Terror",
            "Romance",
            "Suspenso"
        };
        cbxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(generos));
    }

    private void limpiarCampos() {
        txtTitulo.setText("");
        txtDirector.setText("");
        txtActores.setText("");
        txtOrigen.setText("");
        cbxGenero.setSelectedIndex(0);
        dateEstreno.setDate(null);
        botones.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botones = new javax.swing.ButtonGroup();
        panel1 = new java.awt.Panel();
        txtTitulo = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        dateEstreno = new com.toedter.calendar.JDateChooser();
        btnGurardar = new javax.swing.JButton();
        txtDirector = new javax.swing.JTextField();
        txtActores = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtOrigen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbxGenero = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bSi = new javax.swing.JRadioButton();
        bNo = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(153, 0, 51));
        setMinimumSize(new java.awt.Dimension(655, 554));

        panel1.setBackground(new java.awt.Color(51, 51, 51));
        panel1.setForeground(new java.awt.Color(38, 64, 107));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });
        panel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 170, -1));

        btnSalir.setBackground(new java.awt.Color(7, 10, 20));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Salir2.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(153, 153, 153)));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 150, 40));
        panel1.add(dateEstreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 170, -1));

        btnGurardar.setBackground(new java.awt.Color(156, 163, 175));
        btnGurardar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnGurardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Guardar.png"))); // NOI18N
        btnGurardar.setText("Guardar");
        btnGurardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGurardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGurardarActionPerformed(evt);
            }
        });
        panel1.add(btnGurardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 160, 40));

        txtDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirectorActionPerformed(evt);
            }
        });
        panel1.add(txtDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 170, 20));
        panel1.add(txtActores, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 170, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 153, 0));
        jLabel1.setText("Titulo:");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 50, 30));
        panel1.add(txtOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 170, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 153, 0));
        jLabel2.setText("Director:");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 50, 20));

        cbxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxGeneroActionPerformed(evt);
            }
        });
        panel1.add(cbxGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 170, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 153, 0));
        jLabel3.setText("Actores:");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 50, 30));

        jLabel4.setBackground(new java.awt.Color(0, 51, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CREAR.png"))); // NOI18N
        jLabel4.setToolTipText("");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 380, 140));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 153, 0));
        jLabel5.setText("Origen:");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 50, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 153, 0));
        jLabel6.setText("Genero:");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 153, 0));
        jLabel7.setText("Estreno:");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 153, 0));
        jLabel8.setText("En Cartelera:");
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, -1));

        bSi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bSi.setText("Si");
        bSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiActionPerformed(evt);
            }
        });
        panel1.add(bSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        bNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bNo.setText("No");
        bNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNoActionPerformed(evt);
            }
        });
        panel1.add(bNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGurardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGurardarActionPerformed

        String titulo = txtTitulo.getText();
        String director = txtDirector.getText();
        String actor = txtActores.getText();
        String origen = txtOrigen.getText();
        String genero = (String) cbxGenero.getSelectedItem();
        java.util.Date fechaEstreno = dateEstreno.getDate();

        LocalDate fechaLocalEstreno = fechaEstreno.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        if (titulo.isEmpty() || director.isEmpty() || actor.isEmpty() || origen.isEmpty() || genero == null || fechaEstreno == null) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos");
            return;
        }
        Pelicula peli = new Pelicula();
        peli.setTitulo(titulo);
        peli.setDirector(director);
        peli.setActores(actor);
        peli.setOrigen(origen);
        peli.setGenero(genero);
        peli.setEstreno(fechaLocalEstreno);

        boolean encartelera = bSi.isSelected();
        peli.setEnCartelera(encartelera);

        boolean creado = peliculaData.crearPelicula(peli);

        if (creado) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Pelicula " + peli.getTitulo() + " guardado con éxito.",
                    "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
            if (listener != null) {
                listener.actualizarLista();
            }
            return;
        }


    }//GEN-LAST:event_btnGurardarActionPerformed

    private void cbxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGeneroActionPerformed

    }//GEN-LAST:event_cbxGeneroActionPerformed

    private void bSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSiActionPerformed

    private void txtDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirectorActionPerformed

    private void bNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bNoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bNo;
    private javax.swing.JRadioButton bSi;
    private javax.swing.ButtonGroup botones;
    private javax.swing.JButton btnGurardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxGenero;
    private com.toedter.calendar.JDateChooser dateEstreno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private java.awt.Panel panel1;
    private javax.swing.JTextField txtActores;
    private javax.swing.JTextField txtDirector;
    private javax.swing.JTextField txtOrigen;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
