/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas.ComprarEntradas;

import entidades.Comprador;
import entidades.Lugar;
import entidades.Proyeccion;
import java.util.List;
import persistencia.CompradorData;
import persistencia.Context;
import persistencia.LugaresData;
import persistencia.ProyeccionData;
import persistencia.TicketCompraData;

/**
 *
 * @author Morbo
 */
public class Confirmar extends javax.swing.JPanel {

    /**
     * Creates new form Confirmar
     */
    
    private CompradorData compradorData = Context.getCompradorData();
    private ProyeccionData proyeccionData = Context.getProyeccionData();
    private LugaresData lugaresData = Context.getLugaresData();
    private TicketCompraData ticketCompraData = Context.getTicketCompraData();
    
    private Comprador comprador;
    private Proyeccion proyeccion;
    private List<Lugar> lugares;
    
    public void setData (Comprador comprador, Proyeccion proyeccion, List<Lugar> lugares) {
        this.comprador = comprador;
        this.proyeccion = proyeccion;
        this.lugares = lugares;
    }
    
    public Confirmar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(882, 396));

        jLabel1.setText("confirmar");

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 814, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cargarDatos() {
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
