/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas.ComprarEntradas;

import entidades.Comprador;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import listeners.EntradasListener;
import persistencia.CompradorData;
import persistencia.Context;

/**
 *
 * @author Morbo
 */
public class DatosComprador extends javax.swing.JPanel implements EntradasListener {

    /**
     * Creates new form DatosComprador
     */
    private CompradorData compradorData = Context.getCompradorData();

    public DatosComprador() {
        initComponents();
        cbxPago.removeAllItems();
        cbxPago.addItem("Efectivo");
        cbxPago.setEnabled(false);
        txtNombre.setEnabled(false);
        dateFecha.setEnabled(false);
        cbxPago.setEnabled(false);
        lblError.setVisible(false);
    }

    String dni;
    String nombre;
    java.util.Date fechaNac;
    LocalDate fechaNacLocal;
    String modoPago;

    private void obtenerComprador(String dni) {
        Comprador comprador = compradorData.obtenerCompradorPorDni(dni);
        if (comprador != null) {
            lblError.setVisible(false);
            txtNombre.setText(comprador.getNombre());
            dateFecha.setDate(Date.from(comprador.getFechaNac().atStartOfDay(ZoneId.systemDefault()).toInstant()));
            cbxPago.setEnabled(true);
        } else {
            lblError.setVisible(true);
            txtNombre.setText("");
            txtNombre.setEnabled(true);
            dateFecha.setCalendar(null);
            dateFecha.setEnabled(true);
            cbxPago.setSelectedIndex(0);
            cbxPago.setEnabled(true);
        }
    }

    @Override
    public boolean validarDatos() {
        dni = txtDni.getText();
        nombre = txtNombre.getText();
        fechaNac = dateFecha.getDate();
        modoPago = (String) cbxPago.getSelectedItem();

        if (dni.isEmpty() || nombre.isEmpty() || fechaNac == null) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!dni.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "El DNI debe contener solo números", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        fechaNacLocal = fechaNac.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate hoy = LocalDate.now();
        Period edad = Period.between(fechaNacLocal, hoy);
        int anios = edad.getYears();

        if (anios < 18) {
            JOptionPane.showMessageDialog(this, "Debe tener mas de 18 años para comprar una entrada", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (fechaNacLocal.isAfter(LocalDate.now())) {
            JOptionPane.showMessageDialog(this, "La fecha de nacimiento no puede ser futura", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    @Override
    public Comprador guardarDatos() {
        return new Comprador(dni, nombre, fechaNacLocal, modoPago);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblPago = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        dateFecha = new com.toedter.calendar.JDateChooser();
        cbxPago = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 33, 33));
        setMinimumSize(new java.awt.Dimension(882, 396));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(882, 396));

        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/datos.png"))); // NOI18N

        lblDni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDni.setForeground(new java.awt.Color(204, 153, 0));
        lblDni.setText("DNI: ");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(204, 153, 0));
        lblNombre.setText("Nombre:");

        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(204, 153, 0));
        lblFecha.setText("Fecha de nacimiento:");

        lblPago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPago.setForeground(new java.awt.Color(204, 153, 0));
        lblPago.setText("Medio de pago:");

        cbxPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Transferencia", "Tarjeta" }));
        cbxPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPagoActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(7, 10, 20));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(204, 204, 204));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblError.setForeground(new java.awt.Color(255, 51, 51));
        lblError.setText("Comprador no encontrado. Complete sus datos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPago)
                    .addComponent(lblFecha)
                    .addComponent(lblNombre)
                    .addComponent(lblDni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDni)
                            .addComponent(txtNombre)
                            .addComponent(dateFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxPago, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(btnBuscar)))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblError)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPago))
                .addGap(89, 89, 89))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        obtenerComprador(txtDni.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cbxPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPagoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cbxPago;
    private com.toedter.calendar.JDateChooser dateFecha;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPago;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
