/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas.ComprarEntradas;

import entidades.Pelicula;
import entidades.Proyeccion;
import java.util.List;
import javax.swing.JOptionPane;
import listeners.EntradasListener;
import persistencia.Context;
import persistencia.PeliculaData;
import persistencia.ProyeccionData;

/**
 *
 * @author Morbo
 */
public class SeleccionPelicula extends javax.swing.JPanel implements EntradasListener {

    /**
     * Creates new form SeleccionPelicula
     */
    private PeliculaData peliculaData = Context.getPeliculaData();
    private ProyeccionData proyeccionData = Context.getProyeccionData();

    public SeleccionPelicula() {
        initComponents();
        llenarComboPeliculas();
        cbxProyecciones.setEnabled(false);

        cbxPelicula.addActionListener(e -> {
            if (cbxPelicula.getSelectedItem() == null) {
                cbxProyecciones.removeAllItems();
                cbxProyecciones.setEnabled(false);
                return;
            }
            llenarComboProyecciones();
            cbxProyecciones.setEnabled(true);
        });

        cbxProyecciones.addActionListener(e -> {
            if (cbxProyecciones.getSelectedItem() != null) {
                Proyeccion proyeccionSelecionada = (Proyeccion) cbxProyecciones.getSelectedItem();
                txtaDetalles.setText(proyeccionSelecionada.getPelicula().getTitulo());
            } else {
                txtaDetalles.setText("No hay proyecciones disponibles");
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblPelicula = new javax.swing.JLabel();
        lblProyeccion = new javax.swing.JLabel();
        lblLugares = new javax.swing.JLabel();
        cbxPelicula = new javax.swing.JComboBox<>();
        scrDetalles = new javax.swing.JScrollPane();
        txtaDetalles = new javax.swing.JTextArea();
        cbxProyecciones = new javax.swing.JComboBox<>();
        lblLugaresDisponibles = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(882, 396));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(882, 396));

        lblTitulo.setText("seleccionar pelicula");

        lblPelicula.setText("Pelicula:");

        lblProyeccion.setText("Proyeccion:");

        lblLugares.setText("Lugares disponibles");

        txtaDetalles.setColumns(20);
        txtaDetalles.setRows(5);
        scrDetalles.setViewportView(txtaDetalles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scrDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLugares)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblLugaresDisponibles))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblPelicula)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblProyeccion)
                            .addGap(167, 167, 167)
                            .addComponent(cbxProyecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPelicula)
                    .addComponent(cbxPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProyeccion)
                    .addComponent(cbxProyecciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLugares)
                    .addComponent(lblLugaresDisponibles))
                .addGap(32, 32, 32)
                .addComponent(scrDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private int lugares;
    
    private void llenarComboPeliculas() {
        List<Pelicula> peliculas = peliculaData.obtenerTodas();
        cbxPelicula.removeAllItems();
        Pelicula peliculaNull = new Pelicula();
        peliculaNull.setTitulo("Seleccione...");
        cbxPelicula.addItem(peliculaNull);
        for (Pelicula pelicula : peliculas) {
            cbxPelicula.addItem(pelicula);
        }
    }

    private void llenarComboProyecciones() {
        cbxProyecciones.removeAllItems();
        Pelicula peliculaSeleccionada = (Pelicula) cbxPelicula.getSelectedItem();
        List<Proyeccion> proyecciones = proyeccionData.listarProyeccionesPorId(peliculaSeleccionada.getIdPelicula());
        for (Proyeccion proyeccion : proyecciones) {
            cbxProyecciones.addItem(proyeccion);
        }
    }
    
    @Override
    public boolean validarDatos() {
        if(cbxPelicula.getSelectedIndex() == 0) {
             JOptionPane.showMessageDialog(this, "Seleccione una película", "Error", JOptionPane.ERROR);
             return false;
        }
        if(lugares == 0) {
            JOptionPane.showMessageDialog(this, "No hay lugares disponibles en la proyección seleccionada", "Error", JOptionPane.ERROR);
            return false;
        }
        return true;
    }
    
    @Override
    public Proyeccion guardarDatos() {
        Proyeccion proyeccion = new Proyeccion();
        proyeccion.set
        return new Proyeccion();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Pelicula> cbxPelicula;
    private javax.swing.JComboBox<Proyeccion> cbxProyecciones;
    private javax.swing.JLabel lblLugares;
    private javax.swing.JLabel lblLugaresDisponibles;
    private javax.swing.JLabel lblPelicula;
    private javax.swing.JLabel lblProyeccion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane scrDetalles;
    private javax.swing.JTextArea txtaDetalles;
    // End of variables declaration//GEN-END:variables
}
