/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas.ComprarEntradas;

import entidades.Lugar;
import java.util.List;
import javax.swing.JButton;
import persistencia.Context;
import persistencia.LugaresData;

/**
 *
 * @author Morbo
 */
public class SeleccionAsientos extends javax.swing.JPanel {

    /**
     * Creates new form SeleccionAsientos
     */
    private int idProyeccion = -1;
    private LugaresData lugaresData = Context.getLugaresData();

    public void setIdProyeccion(int id) {
        this.idProyeccion = id;
        cargarMapaAsientos();
    }

    public SeleccionAsientos() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("seleccionar asientos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel1)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addContainerGap(199, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void cargarMapaAsientos() {
        System.out.println("Ejecutando sql con la id " + idProyeccion);
        List<Lugar> ocupados = lugaresData.obtenerLugaresOcupados(idProyeccion);

        this.removeAll();
        this.setLayout(new java.awt.GridLayout(4, 6, 5, 5));

        for (char fila = 'A'; fila <= 'D'; fila++) {
            for (int numero = 1; numero <= 6; numero++) {
                boolean estaOcupado = false;
                for (Lugar l : ocupados) {
                    System.out.println(l.getFila() + l.getNumero());
                    if (l.getFila().equals(String.valueOf(fila)) && l.getNumero() == numero) {
                        estaOcupado = true;
                        break;
                    }
                }

                JButton btn = new JButton(fila + String.valueOf(numero));
                btn.setEnabled(!estaOcupado);

                if (estaOcupado) {
                    btn.setBackground(java.awt.Color.RED);
                } else {
                    btn.setBackground(java.awt.Color.GREEN);
                }

                this.add(btn);
            }
        }

        this.revalidate();
        this.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
